<li><a href="index.php">Home</a></li>
<li><a href="krajinky.php">Krajinky</a></li>
<li><a href="nocnifotografie.php">Noční fotografie</a></li>
<li><a href="dronovky.php">Dronovky</a></li>
<li><a href="portrety.php">Portréty</a></li>
<li><a href="me.php">O mně</a></li>
<li><a href="ostatni.php">Ostatní</a></li>
<li><a href="noveZnamky.php">Nové známky</a></li>
<li><a href="znamky.php">Známky</a></li>
